github: opariltay
#bitcoin: 1PVvDhjqkvYoiZQKbpUpgKYXHR4Dv29S5J 
#ethereum: 0x72c9f744fbc52462e3bcff81a4a536efef080639
custom: ["https://blockchair.com/bitcoin/address/1PVvDhjqkvYoiZQKbpUpgKYXHR4Dv29S5J", "https://etherscan.io/address/0x72c9f744fbc52462e3bcff81a4a536efef080639"]
